services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE}
      DJANGO_SETTINGS_MODULE: "core.settings"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "False"
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      FILESYSTEM_DESTINATION_PATH: ${FILESYSTEM_DESTINATION_PATH}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      CATALOGUE_PREFIX: ${CATALOGUE_PREFIX}
      S3_SELF_SIGNED_CERTIFICATE: ${S3_SELF_SIGNED_CERTIFICATE}

    volumes:
      - sqlite_data:/db
      - huey_data:/huey_db

  huey_consumer:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: python manage.py run_huey
    volumes:
      - .:/app
    enviroment:
      FILESYSTEM_DESTINATION_PATH: ${FILESYSTEM_DESTINATION_PATH}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      CATALOGUE_PREFIX: ${CATALOGUE_PREFIX}
      S3_SELF_SIGNED_CERTIFICATE: ${S3_SELF_SIGNED_CERTIFICATE}
    depends_on:
      - django

volumes:
  sqlite_data:
  huey_data:
