FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash appuser

COPY . /app/
RUN chown -R appuser:appuser /app

ENV HOME=/home/appuser
ENV PATH="$HOME/.local/bin:$PATH"

USER appuser

COPY requirements.txt /app/
RUN pip install --user --upgrade pip && \
    pip install --user -r requirements.txt
