FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY . /app/

ENV PATH="$HOME/.local/bin:$PATH"

COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
