# Generated by Django 5.0.6 on 2024-09-17 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('download_strategy', models.CharField(choices=[('video_highest', 'Downloads single videos using ytdlp with highest available quality.'), ('video_playlist_highest', 'Downloads playlist using ytdlp with highest available quality.')], default='video_highest', max_length=50)),
                ('save_strategy', models.CharField(choices=[('s3_save', 'Saves file to the s3 instance.'), ('LOCAL_FILESYSTEM_SAVE', 'Downloads choosen playlist using ytdlp with highest available quality.')], default='LOCAL_FILESYSTEM_SAVE', max_length=50)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
