# Generated by Django 5.0.6 on 2024-09-17 11:33

import downloader.domain.task_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_downloadtask_priority_alter_downloadtask_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='state',
            field=models.CharField(choices=downloader.domain.task_state.TaskState.choices, default='PENDING', max_length=20),
        ),
    ]
