# Generated by Django 5.0.6 on 2024-09-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_downloadtask_catalogue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='download_strategy',
            field=models.CharField(choices=[('audio_highest', 'Downloads single audios using ytdlp with highest available quality.'), ('audio_playlist_highest', 'Downloads audio playlist using ytdlp with highest available quality.'), ('video_highest', 'Downloads single videos using ytdlp with highest available quality.'), ('video_playlist_highest', 'Downloads playlist using ytdlp with highest available quality.')], default='video_highest', max_length=50),
        ),
    ]
