# Generated by Django 5.0.6 on 2024-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_downloadtask_download_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtask',
            name='url',
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='urls',
            field=models.TextField(blank=True, help_text='Enter multiple URLs separated by commas or new lines.'),
        ),
    ]
