# Generated by Django 5.0.6 on 2025-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_alter_downloadtask_save_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='download_strategy',
            field=models.CharField(choices=[('audio_highest', 'Downloads single audios using ytdlp with highest available quality.'), ('audio_playlist_highest', 'Downloads audio playlist using ytdlp with highest available quality.'), ('video_highest', 'Downloads single videos using ytdlp with highest available quality.'), ('video_playlist_highest', 'Downloads videos playlist using ytdlp with highest available quality.'), ('video_list_highest', 'Downloads videos from a list of URLs separated by newlines using ytdlp at the highest available quality.'), ('audio_list_highest', 'Downloads audios from a list of URLs separated by newlines using ytdlp at the highest available quality.')], default='video_highest', max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='save_strategy',
            field=models.CharField(choices=[('LOCAL_FILESYSTEM_SAVE', 'Saves files to the local filesystem.'), ('s3_save', 'Saves file to the s3 instance.')], default='LOCAL_FILESYSTEM_SAVE', max_length=50),
        ),
    ]
