# Generated by Django 5.0.6 on 2025-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_alter_downloadtask_download_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='save_strategy',
            field=models.CharField(choices=[('LOCAL_FILESYSTEM_SAVE', 'Saves files to the local filesystem.'), ('s3_save', 'Saves file to the s3 instance.')], default='s3_save', max_length=50),
        ),
    ]
