# Generated by Django 4.2.6 on 2023-12-29 02:16

from django.db import migrations, models
import mediafetchxpress.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafetchxpress', '0002_alter_group_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=63, unique=True, validators=[mediafetchxpress.models.validate_s3_bucket_name]),
        ),
    ]
